### ISSUE TITLE
Change display time

### ISSUE THREAD

**Issue by JJPimentel91** [Codydanieljones/Service-Now-Alerts#1]
Hi!

The app works great! Just would like to know how to change the time the pop up remains on screen.

Thanks!

**Comment by Codydanieljones** [comment]
Thanks I will look into adding this functionality to the settings page of
the app.

Sent from my Samsung Note.

On Feb 21, 2018 11:00 AM, "JJPimentel91" <notifications@github.com> wrote:

Hi!

The app works great! Just would like to know how to change the time the pop
up remains on screen.

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Codydanieljones/Service-Now-Alerts/issues/1>, or mute
the thread
